import { ExpenseType } from "@/types";
import { Pencil, Bicycle, Books, Robot, RocketLaunch, FirstAid, Club, Detective, Drop, Factory, FireExtinguisher, GameController, GraduationCap, HouseLine, MaskHappy, Park, Pill, PoliceCar, Recycle, RoadHorizon, Scales, Skull, SoccerBall, Stethoscope, Syringe, Television, Toilet, TrafficSign, Train, Trash, Tree, UsersThree, Van, Volleyball, Baby, Popcorn, TrafficSignal, ChalkboardSimple, Brain, Dna, PawPrint, Bird, Flask, ShieldStar, Sun, Atom, AirplaneTilt, CubeFocus, FirstAidKit, Phone, TreePalm } from '@phosphor-icons/react'


export const cityServices: ExpenseType[] = [
  { name: 'Praça',
    desc: 'A praça tem como objetivo de propiciar as pessoas não apenas um local para o lazer, mas também para qualidade de vida, prevenção de doenças, e também como uma forma de sociabilização.',
    category: ['Lazer'],
    value: 1000,
    mensalExpense: 30,
    supply: {
      health: 10,
      leisure: 20,
      education: 0, 
      safety: -10,
      environment: 30,
      mobility: 0,
    },
    icon: Park
  },
  { name: 'Quadra',
    desc: 'Quadras em espaços públicos são uma solução que busca entregar atividades recreativas para a população. Indo além de entretenimento, quadras em espaços públicos também podem significar mais: saúde e bem-estar para a população. Isso porque as quadras esportivas são ambientes em que a prática de esportes é uma constante. ',
    category: ['Lazer'],
    value: 800,
    mensalExpense: 20,
    supply: {
      health: 20,
      leisure: 30,
      education: 10, 
      safety: -10,
      environment: 0,
      mobility: 0,
    },
    icon: Volleyball
  },
  { name: 'Estádio',
    desc: 'Estádios são ótimos espaços para promover o esporte em uma cidade. Podem abrigar jogos e eventos para a população, mas precisam ter demanda e podem gerar problema com cambistas e com as torcidas organizadas.',
    category: ['Lazer'],
    value: 100000,
    mensalExpense: 1000,
    supply: {
      health: 0,
      leisure: 200,
      education: 0, 
      safety: -40,
      environment: 0,
      mobility: -10,
    },
    icon: SoccerBall
  },
  { name: 'Cinema',
    desc: 'O cinema é uma ótima atividade de lazer, seus cidadãos podem assistir os principais blockbusters lançados mundialmente.',
    category: ['Lazer'],
    value: 3000,
    mensalExpense: 150,
    supply: {
      health: 0,
      leisure: 50,
      education: 0, 
      safety: 0,
      environment: 0,
      mobility: -5,
    },
    icon: Popcorn
  },
  { name: 'Teatro',
    desc: 'O teatro, além de ser uma atividade de lazer, forma pessoas mais sensíveis, respeitosas, além de colaborar bastante com a formação de pessoas menos preconceituosas, mais tolerantes e com uma visão mais inteligente sobre tudo.',
    category: ['Lazer'],
    value: 5000,
    mensalExpense: 150,
    supply: {
      health: 0,
      leisure: 50,
      education: 30, 
      safety: 0,
      environment: 0,
      mobility: -5,
    },
    icon: MaskHappy
  },
  { name: 'Cassino',
    desc: 'Os cassinos permitem que sua população se divirta com jogos de azar, e o melhor, sem despesas diretas para a cidade. O maior problema é que o jogo pode viciar, e o jogador compulsivo não destrói apenas a si mesmo, mas causa prejuízos de toda ordem à sua família.',
    category: ['Lazer'],
    value: 1000,
    mensalExpense: 0,
    supply: {
      health: 0,
      leisure: 50,
      education: 0, 
      safety: -60,
      environment: 0,
      mobility: 0,
    },
    icon: Club
  },
  { name: 'Arena de E-games',
    desc: 'As arenas de E-games permitem a realização de torneios ou competições de videogames. É uma ótima diversão, porém, este tipo de esporte pode gerar alguns problemas para os jogadores.',
    category: ['Lazer'],
    value: 30000,
    mensalExpense: 2000,
    supply: {
      health: -60,
      leisure: 400,
      education: 0, 
      safety: -40,
      environment: 0,
      mobility: 0,
    },
    icon: GameController
  },
  { name: 'Centro de reciclagem',
    desc: 'O centro de reciclagem vai garantir a destinação correta dos materiais recicláveis, reinserindo-os na cadeia produtiva, minimizando as demandas por matérias-primas e reduzindo os impactos ambientais da produção.',
    category: ['Ambiente'],
    value: 8000,
    mensalExpense: 400,
    supply: {
      health: 10,
      leisure: 0,
      education: 10, 
      safety: 0,
      environment: 60,
      mobility: 0,
    },
    icon: Recycle
  },
  { name: 'Parque urbano',
    desc: 'Os parques urbanos são áreas verdes que podem trazer qualidade de vida para a população. Pois proporcionam contato com a natureza e suas estruturas e qualidade ambiental, quando adequadas e atrativas, são determinantes para a realização de atividade física e o lazer.',
    category: ['Ambiente'],
    value: 8000,
    mensalExpense: 450,
    supply: {
      health: 20,
      leisure: 60,
      education: 10, 
      safety: 0,
      environment: 90,
      mobility: -10,
    },
    icon: Tree
  },
  { name: 'Metrô',
    desc: 'Metrôs são uma modalidade de transporte público de alta capacidade que utilizam energia elétrica, sendo muito eficientes para regiões muito grandes.',
    category: ['Mobilidade'],
    value: 12000,
    mensalExpense: 400,
    supply: {
      health: 0,
      leisure: 0,
      education: 0, 
      safety: 0,
      environment: 30,
      mobility: 95,
    },
    icon: Train
  },
  { name: 'Pavimentação',
    desc: 'A pavimentação de asfalto é um tipo de revestimento utilizado na construção e manutenção das rodovias, estradas e vias urbanas. Ela permite uma melhor locomoção dos carros pela região.',
    category: ['Mobilidade'],
    value: 500,
    mensalExpense: 30,
    supply: {
      health: 0,
      leisure: 0,
      education: 0, 
      safety: 0,
      environment: 0,
      mobility: 40,
    },
    icon: RoadHorizon
  },
  { name: 'Sinalização',
    desc: 'A sinalização das vias da região permite um tráfico com menos acidentes e cidadãos perdidos.',
    category: ['Mobilidade'],
    value: 300,
    mensalExpense: 20,
    supply: {
      health: 0,
      leisure: 0,
      education: 0, 
      safety: 0,
      environment: 0,
      mobility: 10,
    },
    icon: TrafficSign
  },
  { name: 'Sinalização eletrônica',
    desc: 'A sinalização eletrônica da região permite um tráfico mais eficiente, acelerando o trânsito e evitando acidentes.',
    category: ['Mobilidade'],
    value: 600,
    mensalExpense: 80,
    supply: {
      health: 0,
      leisure: 0,
      education: 0, 
      safety: 0,
      environment: 0,
      mobility: 50,
    },
    icon: TrafficSignal
  },
  { name: 'Ciclovia',
    desc: 'Uma ciclovia ou pista ciclável é um espaço destinado especificamente para a circulação de pessoas utilizando bicicletas. Além de ser um transporte limpo, o uso de bicicletas pela população gera melhoras na saúde.',
    category: ['Mobilidade'],
    value: 500,
    mensalExpense: 20,
    supply: {
      health: 10,
      leisure: 0,
      education: 0, 
      safety: 0,
      environment: 10,
      mobility: 10,
    },
    icon: Bicycle
  },
  { name: 'Ônibus público',
    desc: 'O transporte público é uma boa alternativa de transporte para a população. Menos veículos significa menos engarrafamentos e poluentes emitidos no ambiente.',
    category: ['Mobilidade'],
    value: 1000,
    mensalExpense: 100,
    supply: {
      health: 0,
      leisure: 0,
      education: 0, 
      safety: 0,
      environment: 10,
      mobility: 40,
    },
    icon: Van
  },
  { name: 'Coleta de lixo',
    desc: 'A coleta de lixo é uma medida sanitária fundamental para garantir a saúde da população, evitando a proliferação de doenças relacionadas ao acúmulo do lixo na região.',
    category: ['Ambiente'],
    value: 800,
    mensalExpense: 80,
    supply: {
      health: 20,
      leisure: 0,
      education: 0, 
      safety: 0,
      environment: 30,
      mobility: 0,
    },
    icon: Trash
  },
  { name: 'Tratamento de água',
    desc: 'O processo de tratamento de água a livra de qualquer tipo de contaminação, evitando a transmissão de doenças.',
    category: ['Saúde'],
    value: 1000,
    mensalExpense: 100,
    supply: {
      health: 50,
      leisure: 0,
      education: 0, 
      safety: 0,
      environment: 0,
      mobility: 0,
    },
    icon: Drop
  },
  { name: 'Coleta de esgoto',
    desc: 'A coleta do esgoto evita a transmissão de doenças. Além das questões de saúde, o sistema de coleta e tratamento de esgotos também evita a poluição dos córregos, rios e mares, com a preservação dos recursos hídricos e fontes de abastecimento de água.',
    category: ['Ambiente'],
    value: 800,
    mensalExpense: 80,
    supply: {
      health: 30,
      leisure: 0,
      education: 0, 
      safety: 0,
      environment: 30,
      mobility: 0,
    },
    icon: Toilet
  },
  { name: 'Médico',
    desc: 'Médicos são responsáveis pela prevenção e pela cura dos cidadãos.',
    category: ['Saúde'],
    value: 3000,
    mensalExpense: 300,
    supply: {
      health: 80,
      leisure: 0,
      education: 0, 
      safety: 0,
      environment: 0,
      mobility: 0,
    },
    icon: Stethoscope
  },
  { name: 'Veterinário',
    desc: 'Os bichinhos também merecem cuidado! Veterinários cuidam das saúde dos animais da região, afinal bichinhos também são gente.',
    category: ['Saúde'],
    value: 2500,
    mensalExpense: 200,
    supply: {
      health: 60,
      leisure: 0,
      education: 0, 
      safety: 0,
      environment: 0,
      mobility: 0,
    },
    icon: PawPrint
  },
  { name: 'Programa de vacinação',
    desc: 'Programas de vacinação servem para prevenir surtos de doenças, as vacinas estimulam a produção de anticorpos nas pessoas que combatem agentes infecciosos – como vírus e bactérias – e evitam o adoecimento.',
    category: ['Saúde'],
    value: 300,
    mensalExpense: 200,
    supply: {
      health: 50,
      leisure: 0,
      education: 0, 
      safety: 0,
      environment: 0,
      mobility: 0,
    },
    icon: Syringe
  },
  { name: 'Distribuição de medicamento',
    desc: 'Os medicamentos tem importância vital no tratamento da maioria das doenças, portanto é necessário que o poder público mantenha um adequado sistema de distribuição, buscando assim garantir que o paciente receba os medicamentos de acordo com a prescrição médica.',
    category: ['Saúde'],
    value: 400,
    mensalExpense: 400,
    supply: {
      health: 50,
      leisure: 0,
      education: 0, 
      safety: 0,
      environment: 0,
      mobility: 0,
    },
    icon: Pill
  },
  { name: 'Creche',
    desc: 'As creches públicas são espaços para que crianças ainda sem idade escolar participem de atividades que irão contribuir para sua formação.',
    category: ['Educação'],
    value: 2000,
    mensalExpense: 150,
    supply: {
      health: 20,
      leisure: 0,
      education: 40, 
      safety: 0,
      environment: 0,
      mobility: 0,
    },
    icon: Baby
  },
  { name: 'Escola primária',
    desc: 'É na escola, desde cedo, que a pessoa aprende a socializar, tem contato com uma formação moral e cidadã, além, é claro, da formação intelectual.',
    category: ['Educação'],
    value: 2500,
    mensalExpense: 170,
    supply: {
      health: 0,
      leisure: 0,
      education: 60, 
      safety: 10,
      environment: 0,
      mobility: 0,
    },
    icon: Pencil
  },
  { name: 'Escola secundária',
    desc: 'O ensino médio esina aos estudantes as principais competências para formar bons profissionais.',
    category: ['Educação'],
    value: 6500,
    mensalExpense: 240,
    supply: {
      health: 0,
      leisure: 0,
      education: 80, 
      safety: 20,
      environment: 0,
      mobility: 0,
    },
    icon: ChalkboardSimple
  },
  { name: 'Biblioteca',
    desc: 'A biblioteca funciona como espaço para construção de conhecimento, disponibilizando os recursos necessários para a pesquisa e o descobrimento de novas ideias, realidades, culturas e perspectivas.',
    category: ['Educação'],
    value: 1000,
    mensalExpense: 100,
    supply: {
      health: 0,
      leisure: 20,
      education: 60, 
      safety: 5,
      environment: 0,
      mobility: 0,
    },
    icon: Books
  },
  { name: 'Telecurso',
    desc: 'O Telecurso é uma tecnologia educacional que oferece escolaridade básica de qualidade. Atua na solução de problemas educacionais que impactam nas avaliações nacionais, como distorção idade-série, evasão escolar e defasagem na aprendizagem.',
    category: ['Educação'],
    value: 2000,
    mensalExpense: 100,
    supply: {
      health: 0,
      leisure: 0,
      education: 60, 
      safety: 0,
      environment: 0,
      mobility: 0,
    },
    icon: Television
  },
  { name: 'Viatura policial',
    desc: 'A polícia previne e investiga o crime, gerencia crises e dirime conflitos, facilitando o cotidiano das relações sociais.',
    category: ['Segurança'],
    value: 3000,
    mensalExpense: 340,
    supply: {
      health: 0,
      leisure: 0,
      education: 0, 
      safety: 60,
      environment: 0,
      mobility: 0,
    },
    icon: PoliceCar
  },
  { name: 'Investigador particular',
    desc: 'Detetives particulares podem investigar e até mesmo solucionar casos que sejam de traição, de roubo, de morte ou corrupção.',
    category: ['Segurança'],
    value: 200,
    mensalExpense: 10,
    supply: {
      health: 0,
      leisure: 0,
      education: 0, 
      safety: 10,
      environment: 0,
      mobility: 0,
    },
    icon: Detective
  },
  { name: 'Bombeiro',
    desc: 'Os bombeiros atuam em incêndios, acidentes, desastres e muito mais, salvando vidas e preservando bens.',
    category: ['Segurança'],
    value: 2000,
    mensalExpense: 250,
    supply: {
      health: 0,
      leisure: 0,
      education: 0, 
      safety: 40,
      environment: 0,
      mobility: 0,
    },
    icon: FireExtinguisher
  },
  { name: 'Juiz',
    desc: 'A função do Poder Judiciário é garantir os direitos individuais, coletivos e sociais e resolver conflitos entre cidadãos, entidades e Estado.',
    category: ['Segurança'],
    value: 5000,
    mensalExpense: 850,
    supply: {
      health: 0,
      leisure: 0,
      education: 0, 
      safety: 60,
      environment: 0,
      mobility: 0,
    },
    icon: Scales
  },
  { name: 'Justiçeiro',
    desc: 'Não há evidências conclusivas de que justiçeiros diminuam o crime de forma mais eficaz do que as sentenças de prisão.',
    category: ['Segurança'],
    value: 10000,
    mensalExpense: 1200,
    supply: {
      health: 0,
      leisure: 0,
      education: 0, 
      safety: 30,
      environment: 0,
      mobility: 0,
    },
    icon: Skull
  },
  { name: 'Robo de segurança',
    desc: 'Robos de segurança são equipamentos super avançados que patrulham a região e evitam a prática de crimes.',
    category: ['Segurança'],
    value: 130000,
    mensalExpense: 5200,
    supply: {
      health: 0,
      leisure: 0,
      education: 0, 
      safety: 500,
      environment: 0,
      mobility: 0,
    },
    icon: Robot
  },
  { name: 'Drone voador',
    desc: 'Drones voadores são a última tecnologia em transporte coletivo que existe. Chegue ao seu destino sem congestionamentos ou obstáculos. Um alto preço a pagar pelo que há de melhor!',
    category: ['Mobilidade'],
    value: 350000,
    mensalExpense: 12000,
    supply: {
      health: 0,
      leisure: 0,
      education: 0, 
      safety: 0,
      environment: 0,
      mobility: 2000,
    },
    icon: RocketLaunch
  },
  { name: 'Hospital',
    desc: 'Hospitais são os principais centros de cuidados de saúde e, como tal, desempenham um papel vital na promoção e manutenção da saúde das pessoas.',
    category: ['Saúde'],
    value: 75000,
    mensalExpense: 3000,
    supply: {
      health: 800,
      leisure: 0,
      education: 0, 
      safety: 0,
      environment: 0,
      mobility: 0,
    },
    icon: FirstAid
  },
  { name: 'Faculdade',
    desc: 'Na faculdade são formados profissionais com alta capacidade produtiva.',
    category: ['Educação'],
    value: 40000,
    mensalExpense: 2500,
    supply: {
      health: 0,
      leisure: 0,
      education: 500, 
      safety: 20,
      environment: 0,
      mobility: 0,
    },
    icon: GraduationCap
  },
  { name: 'Centro de pesquisa',
    desc: 'Os centros de pesquisa formam pesquisadores das mais diversas áreas, promovendo o desenvolvimento técnico e humano da região.',
    category: ['Educação'],
    value: 50000,
    mensalExpense: 3500,
    supply: {
      health: 50,
      leisure: 0,
      education: 500, 
      safety: 30,
      environment: 50,
      mobility: 50,
    },
    icon: Flask
  },
  { name: 'Chip neural',
    desc: 'Com os chips neurais a população não precisa mais ir para a escola, todo o conhecimento é acessado pelo chip implantado no cérebro. Ativistas afirmam que este chip controla a mente das pessoas... quem sabe.',
    category: ['Educação'],
    value: 600000,
    mensalExpense: 45500,
    supply: {
      health: 0,
      leisure: 0,
      education: 10000, 
      safety: 0,
      environment: 0,
      mobility: 0,
    },
    icon: Brain
  },
  { name: 'Terapia genética',
    desc: 'Com as terapias genéticas não há mais doenças incuráveis, diante de qualquer problema de saúde é só o paciente alterar o seu DNA e está tudo resolvido.',
    category: ['Saúde'],
    value: 750000,
    mensalExpense: 60000,
    supply: {
      health: 10000,
      leisure: 0,
      education: 0, 
      safety: 0,
      environment: 0,
      mobility: 0,
    },
    icon: Dna
  },
  { name: 'Área de preservação',
    desc: 'As áreas de preservação permitem o desenvolvimento da fauna e da flora regional. Colaborando para o equilíbrio e recuperação ambiental.',
    category: ['Ambiente'],
    value: 10000,
    mensalExpense: 600,
    supply: {
      health: 20,
      leisure: 0,
      education: 0, 
      safety: 0,
      environment: 100,
      mobility: 0,
    },
    icon: Bird
  },
  { name: 'Delegacia de polícia',
    desc: 'Cada delegacia conta com dezenas de policiais prontos para a ação. Seja na prevenção ou na repressão do crime.',
    category: ['Segurança'],
    value: 30000,
    mensalExpense: 2500,
    supply: {
      health: 0,
      leisure: 0,
      education: 0, 
      safety: 400,
      environment: 0,
      mobility: 0,
    },
    icon: ShieldStar
  },
  { name: 'Energia limpa',
    desc: 'A energia solar reduz drasticamente a poluição em carros, casas e indústrias na cidade.',
    category: ['Ambiente'],
    value: 30000,
    mensalExpense: 2500,
    supply: {
      health: 0,
      leisure: 0,
      education: 0, 
      safety: 0,
      environment: 400,
      mobility: 0,
    },
    icon: Sun
  },
  { name: 'Reciclagem atômica',
    desc: 'Esta é a última tecnologia em recomposição ambiental. Com o sistema de reciclagem atômica as moléculas de carbono são convertidas em oxigênio como um passe de mágica.',
    category: ['Ambiente'],
    value: 1000000,
    mensalExpense: 10000,
    supply: {
      health: 0,
      leisure: 0,
      education: 0, 
      safety: 0,
      environment: 4000,
      mobility: 0,
    },
    icon: Atom
  },
  { name: 'Avião',
    desc: 'Ter um aeroporto na região é uma ótima opção para atrair turistas e negócios.',
    category: ['Mobilidade'],
    value: 20000,
    mensalExpense: 1500,
    supply: {
      health: 0,
      leisure: 0,
      education: 0, 
      safety: 0,
      environment: -50,
      mobility: 250,
    },
    icon: AirplaneTilt
  },
  { name: 'Metaverso',
    desc: 'Para que se preocupar com o mundo real quando no mundo virtual tudo é perfeito. Com o metaverso a população não tem que sair de casa para se divertir até não aguentar mais.',
    category: ['Lazer'],
    value: 300000,
    mensalExpense: 8000,
    supply: {
      health: -70,
      leisure: 2000,
      education: 0, 
      safety: 0,
      environment: 0,
      mobility: 0,
    },
    icon: CubeFocus
  },
  { name: 'Agente de saúde',
    desc: 'Saúde preventiva é a melhor opção para evitar problemas de saúde. Os agentes de saúde passam de porta em porta avaliando as pessoas e prescrevendo medidas para melhorar a sua qualidade de vida.',
    category: ['Saúde'],
    value: 2000,
    mensalExpense: 150,
    supply: {
      health: 60,
      leisure: 0,
      education: 0, 
      safety: 0,
      environment: 0,
      mobility: 0,
    },
    icon: FirstAidKit
  },
  { name: 'Central de emergências',
    desc: 'A central de emergências recebe ligações da população e encaminha a solução para o departamento responsável. Seja um incêncio, um assalto ou um gatinho preso na árvore.',
    category: ['Segurança'],
    value: 2000,
    mensalExpense: 150,
    supply: {
      health: 60,
      leisure: 0,
      education: 0, 
      safety: 0,
      environment: 0,
      mobility: 0,
    },
    icon: Phone
  },
  { name: 'Planta ornamental',
    desc: 'Se você acredita que plantando uma árvore diferentona no canteiro da avenida você está salvando o planeta, essa é a sua solução. Palmeiras, coqueiros e cerejeiras, deixe a cidade mais verde com as plantas ornamentais.',
    category: ['Ambiente'],
    value: 100,
    mensalExpense: 10,
    supply: {
      health: 0,
      leisure: 0,
      education: 0, 
      safety: 0,
      environment: 5,
      mobility: 0,
    },
    icon: TreePalm
  },
 ] 